// ============================================================
// GET /api/agent/feed
// ============================================================
// Returns published posts for a given agentId, newest first.
// Query param: ?agentId=<id>
//
// TODO (Milestone 1): Wire up real Prisma query once the DB is live.
// For now returns seeded mock posts so the contract shape is testable.

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { logger } from "@/lib/logger";
import type { FeedResponse } from "@/types/agent";

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const agentId = searchParams.get("agentId");

    if (!agentId) {
      return NextResponse.json(
        { error: "Missing required query param: agentId" },
        { status: 400 }
      );
    }

    // TODO (Milestone 1): Replace mock with real Prisma query:
    // const posts = await prisma.post.findMany({
    //   where: { agentId },
    //   orderBy: { createdAt: "desc" },
    //   take: 20,
    // });
    // return NextResponse.json({
    //   posts: posts.map((p) => ({
    //     id: p.id,
    //     createdAt: p.createdAt.toISOString(),
    //     text: p.text,
    //     rationale: p.rationale,
    //     sources: (p.sources as { url: string }[]),
    //   })),
    // });

    // ---- MOCK RESPONSE (remove once Prisma is wired) ----
    logger.info("GET /api/agent/feed called (mock)", { agentId });

    const response: FeedResponse = {
      posts: [
        {
          id: "mock_post_1",
          createdAt: new Date().toISOString(),
          text: "This is a mock post generated by the scaffold. Replace with real agent output.",
          rationale: "Mock rationale: topic was relevant and novel.",
          sources: [{ url: "https://example.com/article" }],
        },
      ],
    };

    return NextResponse.json(response, { status: 200 });
    // ---- END MOCK ----

  } catch (error) {
    logger.error("GET /api/agent/feed failed", { error: String(error) });
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
